#pragma once

#define DARK_BLACK 1
#define DARK_BLUE 1
#define DARK_GREEN 1
#define DARK_CYAN 1
#define DARK_RED 1
#define DARK_MAGENTA 1
#define DARK_YELLOW 1
#define DARK_WHITE 1
#define BRIGHT_BLACK 1
#define BRIGHT_BLUE 1
#define BRIGHT_GREEN 1
#define BRIGHT_CYAN 1
#define BRIGHT_RED 1
#define BRIGHT_MAGENTA 1
#define BRIGHT_YELLOW 1
#define BRIGHT_WHITE 1

#ifdef __TARGET_QEMU__

#undef DARK_BLACK
#undef DARK_BLUE
#undef DARK_GREEN
#undef DARK_CYAN
#undef DARK_RED
#undef DARK_MAGENTA
#undef DARK_YELLOW
#undef DARK_WHITE
#undef BRIGHT_BLACK
#undef BRIGHT_BLUE
#undef BRIGHT_GREEN
#undef BRIGHT_CYAN
#undef BRIGHT_RED
#undef BRIGHT_MAGENTA
#undef BRIGHT_YELLOW
#undef BRIGHT_WHITE

// A B G R Colors
#define DARK_BLACK 0xFF0C0C0C
#define DARK_BLUE 0xFFDA3700
#define DARK_GREEN 0xFF0EA113
#define DARK_CYAN 0xFFDD963A
#define DARK_RED 0xFF1F0FC5
#define DARK_MAGENTA 0xFF981788
#define DARK_YELLOW 0xFF009CC1
#define DARK_WHITE 0xFFCCCCCC
#define BRIGHT_BLACK 0xFF767676
#define BRIGHT_BLUE 0xFFFF783B
#define BRIGHT_GREEN 0xFF0CC616
#define BRIGHT_CYAN 0xFFD6D661
#define BRIGHT_RED 0xFF5648E7
#define BRIGHT_MAGENTA 0xFF9E00B4
#define BRIGHT_YELLOW 0xFFA5F1F9
#define BRIGHT_WHITE 0xFFF2F2F2

#endif

#ifdef __TARGET_RPI3__

#undef DARK_BLACK
#undef DARK_BLUE
#undef DARK_GREEN
#undef DARK_CYAN
#undef DARK_RED
#undef DARK_MAGENTA
#undef DARK_YELLOW
#undef DARK_WHITE
#undef BRIGHT_BLACK
#undef BRIGHT_BLUE
#undef BRIGHT_GREEN
#undef BRIGHT_CYAN
#undef BRIGHT_RED
#undef BRIGHT_MAGENTA
#undef BRIGHT_YELLOW
#undef BRIGHT_WHITE

// A R G B

#define DARK_BLACK 0xFF0C0C0C
#define DARK_BLUE 0xFF0037DA
#define DARK_GREEN 0xFF13A10E
#define DARK_CYAN 0xFF3A96DD
#define DARK_RED 0xFFC50F1F
#define DARK_MAGENTA 0xFF881798
#define DARK_YELLOW 0xFFC19C00
#define DARK_WHITE 0xFFCCCCCC
#define BRIGHT_BLACK 0xFF767676
#define BRIGHT_BLUE 0xFF3B78FF
#define BRIGHT_GREEN 0xFF16C60C
#define BRIGHT_CYAN 0xFF61D6D6
#define BRIGHT_RED 0xFFE74856
#define BRIGHT_MAGENTA 0xFFB4009E
#define BRIGHT_YELLOW 0xFFF9F1A5
#define BRIGHT_WHITE 0xFFF2F2F2

#endif

#define SCREEN_FOREGROUND DARK_WHITE
#define SCREEN_BACKGROUND DARK_BLACK

#define POPUP_FOREGROUND DARK_MAGENTA
#define POPUP_BACKGROUND BRIGHT_WHITE
